### ISSUE TITLE
[Feature] Package.json analysis

### ISSUE THREAD

**Issue by nekloth** [egoist/npm-size#1]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24200%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/npm-size/issues/1)

Hello

I have a feature request. 

Instead of having to list the packages you want to size-analyze, it could be very interesting to have your project package analyzed.

For instance:
```
> npm-size --package
Dependencies:
  √ zen-observable  71.7 kB
Dev-dependencies:
  √ cac             49.2 kB
  √ chalk           86.2 kB
  √ commitizen      8.67 MB
  √ conf            128 kB
  √ execa           191 kB
  √ husky           1.27 MB
  √ prettier        9.12 MB
  √ yarn            4.91 MB
```

What do you think?

(BTW, thank you for the job done!)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $200.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($200.00)
### Submitted pull Requests
- [#3 Implement the --package option.](https://issuehunt.io/r/egoist/npm-size/pull/3)
- [#2 feat: scan package.json](https://issuehunt.io/r/egoist/npm-size/pull/2)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/npm-size/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by satyarohith** [comment]
@egoist Shall I work on this?
