### ISSUE TITLE
Ironically bad install size

### ISSUE THREAD

**Issue by jaydenseric** [egoist/npm-size#5]
`npm-size` has a huge 5.62 MB install size:

https://packagephobia.now.sh/result?p=npm-size@1.3.0

What is even worse, the dependencies are defined as dev dependencies and bundled into the published code, instead of using normal package dependencies!

https://unpkg.com/browse/npm-size@1.3.0/dist/cli.js

This is an antipattern that causes `node_modules` to bloat if consumers already have those dependencies installed.

I don't get it, why is this project so complicated? Just install a package to a directory in `os.tmpdir()`, see how big it is, then clean it up. That should be less than 20 lines, and perhaps no dependencies to achieve.

**Comment by egoist** [comment]
You're welcome to try implementing a 20-line npm-size alternative.
